[workspace]
members = ["section_01_basics/ch_01_hello_world", "section_01_basics/ch_02_types_variables"
, "section_01_basics/ch_03_functions", "section_01_basics/ch_04_modules", "section_01_basics/exercise_module", "section_02_control_ownership/ch_01_if_else", "section_02_control_ownership/ch_02_match", "section_02_control_ownership/ch_03_loop", "section_02_control_ownership/ch_04_stack_heap", "section_02_control_ownership/exercise"]


resolver = "2"

